import type { SpeciesAuthorityPage } from "./types.ts";

const c = (sourceId: string, locator?: string) => ({ sourceId, ...(locator ? { locator } : {}) });

export const whiteTailedDeerAuthorityPage: SpeciesAuthorityPage = {
  schemaVersion: "1.0.0",
  speciesId: "species:white-tailed-deer",
  slug: "white-tailed-deer",
  canonicalPath: "/hunting/species/white-tailed-deer",
  status: "REFERENCE_IMPLEMENTATION",
  huntingCompatibility: "HUNTABLE",
  reviewedAt: "2026-10-06",
  identity: {
    commonName: "White-tailed deer",
    scientificName: "Odocoileus virginianus",
    frenchName: "Cerf de Virginie",
    family: "Cervidae",
    directAnswer: "A highly adaptable North American deer identified most reliably by the broad white underside of its tail, which it raises as a flag when alarmed. Biology can help you find and identify deer; only the responsible authority can say whether a particular animal is legal to hunt.",
  },
  facts: [
    { label: "Best field mark", value: "Broad white tail underside; tail often raised when alarmed", sourceIds: ["source:ndgf-whitetail"] },
    { label: "Food", value: "A seasonally flexible browser: woody browse, forbs, mast and crops", sourceIds: ["source:usfs-feis-whitetail"] },
    { label: "Peak activity", value: "Often crepuscular; pressure and local conditions can shift movement", sourceIds: ["source:ndgf-whitetail", "source:usfs-feis-whitetail"] },
    { label: "Habitat pattern", value: "Edges and mosaics that place forage close to escape and thermal cover", sourceIds: ["source:usfs-feis-whitetail"] },
    { label: "Track", value: "Two pointed, heart-shaped hoof impressions; size and substrate vary", sourceIds: ["source:mdc-whitetail"] },
    { label: "Range", value: "Broad North American range; local occurrence and density are uneven", sourceIds: ["source:hww-whitetail"] },
  ],
  sectionOrder: ["overview", "identification", "habitat", "diet", "behaviour", "tracks-and-sign", "seasonal-pattern", "how-to-hunt", "shot-placement", "equipment", "regulations", "range-and-map", "faq", "sources"],
  sections: [
    { id: "overview", title: "Overview", shortTitle: "Overview", layer: "BIOLOGY", directAnswer: "White-tailed deer succeed across a remarkable range of landscapes because they adjust food, cover use and movement to local seasons and disturbance.", claims: [
      { id: "overview-adaptable", text: "The species occupies forests, farms, shrublands, wetlands and developed edges; the useful unit for fieldwork is the local cover-and-food pattern, not a generic habitat label.", citations: [c("source:usfs-feis-whitetail", "Habitat and plant communities")] },
      { id: "overview-variation", text: "Body size, antler development, timing and behaviour vary across latitude, nutrition, age and local conditions. Treat regional averages as context, never as an identification test.", citations: [c("source:hww-whitetail"), c("source:ndgf-whitetail")] },
    ] },
    { id: "identification", title: "Identification", shortTitle: "ID", layer: "BIOLOGY", directAnswer: "Confirm the tail, rump, ears, antlers and gait together. Do not identify a deer from antlers or apparent body size alone.", claims: [
      { id: "id-coat", text: "Adults are reddish-brown in summer and grey-brown in winter; fawns are spotted. The throat, belly, inner legs and underside of the tail carry conspicuous white.", citations: [c("source:ndgf-whitetail", "Description")] },
      { id: "id-antlers", text: "Adult males usually grow antlers with tines rising from a main beam. Antler size is strongly affected by age and nutrition and is not a dependable age measure by itself.", citations: [c("source:hww-whitetail", "Description")] },
    ], subsections: [
      { id: "similar-species", title: "Similar species", directAnswer: "Where ranges overlap, separate white-tailed deer from mule deer by combining tail pattern, ear proportions, antler branching and escape gait.", claims: [
        { id: "id-mule-deer", text: "Mule deer typically show larger ears, a narrower white tail with a black tip, forked antlers and a bounding or stotting escape gait; white-tailed deer more often run with the broad white tail raised.", citations: [c("source:ndgf-whitetail", "Identification") ] },
      ], caution: "If the species, sex, age class or antler class is uncertain, do not shoot. Legal definitions are jurisdiction-specific." },
      { id: "sex-and-age", title: "Sex and age", directAnswer: "Use several body traits at close, unhurried range; biological sex and age are not substitutes for the legal animal-class definition.", claims: [
        { id: "id-sex-age", text: "Neck, chest, belly line, leg-to-body proportions and behaviour can support an estimate. Obscured antlers, shed antlers and young males make single-feature decisions unsafe.", citations: [c("source:ontario-deer-guide", "Identification and harvest selection")] },
      ] },
    ] },
    { id: "habitat", title: "Habitat", shortTitle: "Habitat", layer: "BIOLOGY", directAnswer: "The strongest white-tail habitat puts food near secure cover. Productive edges matter, but an edge with no usable forage or refuge is just a line on a map.", claims: [
      { id: "habitat-mosaic", text: "Mixed woodland, regenerating cuts, old fields, riparian corridors, cropland margins and brush can form useful mosaics when forage, concealment and seasonal shelter occur close together.", citations: [c("source:usfs-feis-whitetail", "Preferred habitat")] },
      { id: "habitat-north", text: "In northern winters, conifer shelter can reduce wind and snow costs while nearby browse supplies food. Winter concentration areas should not be disturbed unnecessarily.", citations: [c("source:maine-whitetail", "Winter habitat")] },
    ], subsections: [
      { id: "habitat-reading", title: "How to read habitat", directAnswer: "Start with transitions: bedding cover to feeding cover, upland to wet ground, mature timber to regeneration, or a barrier that narrows travel.", claims: [
        { id: "habitat-transition", text: "Aerial imagery proposes a pattern; tracks, pellets, browse, beds and current trails must confirm that deer are using it now.", citations: [c("source:indiana-scouting", "Where to scout")] },
      ] },
    ] },
    { id: "diet", title: "Diet", shortTitle: "Diet", layer: "BIOLOGY", directAnswer: "White-tailed deer are selective, flexible feeders. The locally important food changes with plant community, weather and season.", claims: [
      { id: "diet-foods", text: "Diet may include leaves and stems of woody plants, forbs, grasses, fungi, fruits, nuts and agricultural crops. Mast such as acorns can reorganize autumn movement where it is abundant.", citations: [c("source:usfs-feis-whitetail", "Food habits")] },
      { id: "diet-browse", text: "Browsed twig tips, clipped vegetation and a visible browse line can show repeated feeding, but they are not species proof without tracks, pellets or direct observation.", citations: [c("source:wdfw-deer", "Signs")] },
    ], subsections: [
      { id: "stomach-contents", title: "Field observation: stomach contents", directAnswer: "Stomach contents can record what one harvested animal ate recently; they do not define the species' full diet or prove that a food is important across the season.", claims: [{ id: "diet-stomach-observation", text: "Where examination is lawful and appropriate, record identifiable material, location, date and uncertainty. Treat the observation as a local clue to compare with available plants and browse—not as a recipe for other places or times.", citations: [c("source:usfs-feis-whitetail", "Food habits")] }], caution: "Use gloves and follow local carcass-handling, testing and disposal guidance. Never taste unknown plant material or infer food safety from deer use." },
    ] },
    { id: "behaviour", title: "Behaviour", shortTitle: "Behaviour", layer: "FIELD_KNOWLEDGE", directAnswer: "Movement is often strongest around dawn and dusk, but cover, weather, food, breeding and human pressure can move activity into other hours or denser cover.", claims: [
      { id: "behaviour-activity", text: "White-tails commonly use familiar home ranges and travel routes. They may tighten movement, favour thicker cover or become more nocturnal where disturbance is repeated.", citations: [c("source:usfs-feis-whitetail", "Cover and human disturbance"), c("source:ndgf-whitetail", "Habits")] },
      { id: "behaviour-alarm", text: "A raised flagging tail, abrupt snort or bounding retreat signals alarm. Freeze, identify the wind and avoid pushing deer toward roads, property boundaries or other hunters.", citations: [c("source:hww-whitetail", "Behaviour")] },
    ] },
    { id: "tracks-and-sign", title: "Tracks and sign", shortTitle: "Sign", layer: "FIELD_KNOWLEDGE", directAnswer: "A single track says a deer passed. Direction, freshness, repetition and the surrounding cover are what turn sign into useful field knowledge.", claims: [
      { id: "sign-tracks", text: "Typical tracks show two pointed toes and an overall heart shape. Soft ground, speed and splayed toes can enlarge or distort them, so dimensions are supporting evidence only.", citations: [c("source:mdc-whitetail", "Tracks")] },
      { id: "sign-rubs", text: "Rubs are bark-scraped stems associated mainly with antlered deer. Scrapes are pawed ground often beneath an overhanging branch. Neither guarantees daylight use or an animal's current location.", citations: [c("source:indiana-scouting", "Rubs and scrapes")] },
    ], subsections: [
      { id: "sign-interpretation", title: "Interpret sign in context", directAnswer: "Look for converging evidence: several fresh tracks, current droppings, browsed plants and a trail connecting known cover or food.", claims: [
        { id: "sign-freshness", text: "Moist edges, sharp detail, displaced leaves and sign laid over recent weather can suggest recency, but substrate and exposure change ageing quickly. State uncertainty plainly.", citations: [c("source:indiana-scouting", "Scouting basics")] },
      ] },
    ] },
    { id: "seasonal-pattern", title: "Seasonal pattern", shortTitle: "Season", layer: "FIELD_KNOWLEDGE", directAnswer: "Season changes what deer need most: emerging forage in spring, security and growth in summer, breeding movement in autumn, and energy conservation plus shelter in winter.", claims: [
      { id: "season-spring-summer", text: "Spring green-up and summer cover spread feeding opportunities. Does use secluded cover around fawning; observe from distance and leave apparently hidden fawns alone.", citations: [c("source:hww-whitetail", "Life cycle")] },
      { id: "season-autumn", text: "Breeding occurs in autumn across much of the range, but peak timing and visible movement vary geographically and locally. Photoperiod is important; weather and pressure affect what hunters observe.", citations: [c("source:ndgf-whitetail", "Reproduction"), c("source:ontario-deer-guide", "Deer biology")] },
      { id: "season-winter", text: "Cold, deep snow and declining food can concentrate deer in sheltered habitat. Repeated disturbance then costs energy and can damage sensitive wintering areas.", citations: [c("source:maine-whitetail", "Winter survival")] },
    ] },
    { id: "how-to-hunt", title: "How to hunt", shortTitle: "Hunt", layer: "HUNTING_INTELLIGENCE", directAnswer: "Find a current food-cover-travel relationship, confirm legal access and wind, then choose a low-impact position that offers a close, controlled shot.", claims: [
      { id: "hunt-scout", text: "Scout from large pattern to small proof: locate habitat transitions and funnels, then verify fresh sign and a safe approach before committing to a setup.", citations: [c("source:indiana-scouting", "Scouting strategies")] },
      { id: "hunt-wind", text: "Plan entry and exit around the wind and expected deer path. Avoid crossing the trail, bedding edge or feeding area you intend to observe.", citations: [c("source:ontario-deer-guide", "Hunting techniques and safety")] },
    ], subsections: [
      { id: "still-hunting", title: "Still-hunting", directAnswer: "Move slower than feels necessary, glass first and use cover to break your outline; stop more than you walk.", claims: [{ id: "hunt-still", text: "Still-hunting works best when wind, wet ground or soft snow reduce noise and visibility is sufficient to identify a deer and backstop before raising a firearm or bow.", citations: [c("source:ontario-deer-guide", "Hunting techniques")] }] },
      { id: "stand-and-ambush", title: "Stand or ground ambush", directAnswer: "Set up downwind of a verified route, not directly on it, and retain a safe shot lane and exit.", claims: [{ id: "hunt-stand", text: "Funnels, crossings and inside corners can concentrate travel, but stale sign and attractive map geometry do not replace present field evidence.", citations: [c("source:indiana-scouting", "Funnels and travel corridors")] }] },
    ] },
    { id: "shot-placement", title: "Ethical shot placement", shortTitle: "Shot", layer: "HUNTING_INTELLIGENCE", directAnswer: "Wait for a broadside or modest quartering-away presentation that exposes the heart-lung area, with a clear path and safe backstop. If any part is uncertain, do not shoot.", claims: [
      { id: "shot-vitals", text: "Aim through the centre of the chest's heart-lung area, accounting for the near and far legs and the animal's angle. The intended path matters more than a surface mark on the hide.", citations: [c("source:illinois-shot", "Heart and lungs") ] },
      { id: "shot-avoid", text: "Avoid head, neck, spine-only, rear-facing and steep quartering-to shots. They offer small targets, heavy bone or a poor path through both lungs and carry a higher wounding risk.", citations: [c("source:illinois-shot", "Shot angles") ] },
      { id: "shot-followup", text: "After the shot, mark the exact location, watch the direction of travel, wait an appropriate interval and follow local retrieval rules. Never assume a miss because a deer did not fall immediately.", citations: [c("source:ontario-deer-guide", "After the shot") ] },
    ], subsections: [
      { id: "shot-visual", title: "How to use the visual", directAnswer: "Choose the angle first, then use the broad target region to visualize a path through the chest. Only the registered quartering-away pair offers an anatomy toggle.", claims: [{ id: "shot-visual-contract", text: "Broadside uses an external-only view because its separate anatomy plate does not register to the same pose. Frontal and quartering-toward target plates are withheld because they conflict with the sourced pass decision.", citations: [c("source:illinois-shot", "Anatomy and angles") ] }], caution: "Every shot depends on angle, distance, equipment, the hunter's capability, a clear target and what lies beyond." },
    ] },
    { id: "equipment", title: "Equipment", shortTitle: "Gear", layer: "HUNTING_INTELLIGENCE", directAnswer: "Use legal, well-maintained equipment that you can place accurately at the distance and angle offered. Regulation, proficiency and field conditions matter more than brand or maximum range.", claims: [
      { id: "equipment-core", text: "Core field equipment includes an appropriate legal hunting implement and ammunition or arrows, positive identification optics, blaze clothing where required, navigation, weather protection, first aid and a retrieval plan.", citations: [c("source:ontario-deer-guide", "Equipment and safety")] },
      { id: "equipment-practice", text: "Confirm zero or tune, practice from realistic field positions and set a personal maximum distance based on repeatable groups—not the equipment's advertised capability.", citations: [c("source:illinois-shot", "Preparation and shot selection")] },
    ] },
    { id: "regulations", title: "Regulations", shortTitle: "Rules", layer: "REGULATORY_HANDOFF", directAnswer: "This page does not tell you that a hunt is legal. A legal answer requires the exact place, date, licence, season, animal class, method and current authority source.", claims: [
      { id: "rules-separation", text: "White-tailed deer are managed as game in many jurisdictions, but seasons, zones, tags, antler definitions, legal methods and reporting duties differ and change. Use Hunt for the covered place and date, then read the linked authority.", citations: [c("source:ontario-hunting-regulations", "Deer seasons and requirements")] },
      { id: "rules-access", text: "A season does not grant access. Confirm land ownership, permission, discharge restrictions, protected areas and local rules separately.", citations: [c("source:ontario-hunting-regulations", "General regulations")] },
    ] },
    { id: "range-and-map", title: "Range and map", shortTitle: "Map", layer: "GEOSPATIAL_INTELLIGENCE", directAnswer: "North Ground's Species Heat layer shows range-constrained habitat opportunity—not animals, population density, property access or an open season.", claims: [
      { id: "map-range", text: "White-tailed deer occur broadly across southern Canada, most of the continental United States and farther south, but distribution and abundance are patchy and change with habitat and climate.", citations: [c("source:hww-whitetail", "Range")] },
      { id: "map-model", text: "The current North Ground layer is a production-verified RANGE_HABITAT surface at approximately 11 km habitat resolution. Its confidence is moderate and its source age is reported as ageing; use it to choose where to investigate, then verify in the field.", citations: [c("source:north-ground-whitetail-surface", "surface:range-habitat-white-tailed-deer-2.1.0")] },
    ] },
    { id: "faq", title: "Frequently asked questions", shortTitle: "FAQ", layer: "FIELD_KNOWLEDGE", directAnswer: "Short answers to the field questions most likely to change an identification, scouting or ethical-shot decision.", claims: [] },
    { id: "sources", title: "Sources and review", shortTitle: "Sources", layer: "BIOLOGY", directAnswer: "Claims are linked to biological, field, hunting-education, regulatory and geospatial sources. Source type is shown because one kind of evidence cannot silently answer another kind of question.", claims: [] },
  ],
  faq: [
    { id: "faq-tail", question: "Is every deer with white on its tail a white-tailed deer?", directAnswer: "No. Confirm the broad white underside and use rump pattern, ears, antlers, gait and local range together.", citations: [c("source:ndgf-whitetail", "Identification")] },
    { id: "faq-rut", question: "When is the white-tail rut?", directAnswer: "Autumn across much of the range, but timing varies by latitude and local population. Do not treat one calendar week as universal.", citations: [c("source:ndgf-whitetail", "Reproduction")] },
    { id: "faq-track", question: "Can track size identify a buck?", directAnswer: "No. Substrate, gait and individual size overlap; a large track may support an interpretation but cannot establish sex by itself.", citations: [c("source:mdc-whitetail", "Tracks")] },
    { id: "faq-map", question: "Does a hot map cell mean deer are there?", directAnswer: "No. It means the model found comparatively stronger range-constrained habitat opportunity at its stated resolution—not a current animal count.", citations: [c("source:north-ground-whitetail-surface", "Limitations")] },
    { id: "faq-legal", question: "Does this page mean I can hunt white-tailed deer here today?", directAnswer: "No. Check the exact location and date in Hunt and verify the linked authority, licence, access, method and animal-class requirements.", citations: [c("source:ontario-hunting-regulations", "Deer seasons and requirements")] },
  ],
  sources: [
    { id: "source:hww-whitetail", title: "White-tailed Deer", publisher: "Hinterland Who's Who / Canadian Wildlife Federation", url: "https://www.hww.ca/en/wildlife/mammals/white-tailed-deer.html", kind: "BIOLOGICAL", reviewedAt: "2026-10-06", note: "Canadian biology, range, life cycle and behaviour overview." },
    { id: "source:usfs-feis-whitetail", title: "Odocoileus virginianus: Fire Effects Information System species review", publisher: "U.S. Forest Service", url: "https://research.fs.usda.gov/feis/species-reviews/odvi", kind: "BIOLOGICAL", reviewedAt: "2026-10-06", note: "Research synthesis for habitat, food habits, cover and regional variation." },
    { id: "source:ndgf-whitetail", title: "White-tailed Deer", publisher: "North Dakota Game and Fish Department", url: "https://gf.nd.gov/wildlife/id/ungulates/white-tailed-deer", kind: "BIOLOGICAL", reviewedAt: "2026-10-06", note: "Identification, description, food, habits and reproduction." },
    { id: "source:mdc-whitetail", title: "White-tailed Deer field guide", publisher: "Missouri Department of Conservation", url: "https://mdc.mo.gov/discover-nature/field-guide/white-tailed-deer", kind: "FIELD_GUIDANCE", reviewedAt: "2026-10-06", note: "Track form, dimensions and field signs." },
    { id: "source:indiana-scouting", title: "Deer scouting basics", publisher: "Indiana Department of Natural Resources", url: "https://www.in.gov/dnr/fish-and-wildlife/wildlife-resources/animals/white-tailed-deer/deer-scouting-basics/", kind: "FIELD_GUIDANCE", reviewedAt: "2026-10-06", note: "Trails, funnels, rubs, scrapes and sign interpretation." },
    { id: "source:wdfw-deer", title: "Deer species facts", publisher: "Washington Department of Fish and Wildlife", url: "https://wdfw.wa.gov/species-habitats/living/species-facts/deer", kind: "FIELD_GUIDANCE", reviewedAt: "2026-10-06", note: "Tracks, trails, browse and coexistence signs." },
    { id: "source:maine-whitetail", title: "White-tailed Deer", publisher: "Maine Department of Inland Fisheries & Wildlife", url: "https://www.maine.gov/ifw/fish-wildlife/wildlife/species-information/mammals/deer.html", kind: "BIOLOGICAL", reviewedAt: "2026-10-06", note: "Northern winter habitat, diet and survival context." },
    { id: "source:illinois-shot", title: "Taking Your Shot", publisher: "Illinois Natural History Survey", url: "https://hunt.inhs.illinois.edu/hunting-trapping/deer-hunting/taking-your-shot/", kind: "HUNTING_EDUCATION", reviewedAt: "2026-10-06", note: "Anatomy, heart-lung target, shot angles and ethical selection." },
    { id: "source:ontario-deer-guide", title: "White-tailed deer hunting guide", publisher: "Government of Ontario", url: "https://docs.ontario.ca/documents/2811/guide-whitetail-deer.pdf", kind: "HUNTING_EDUCATION", reviewedAt: "2026-10-06", note: "Ontario deer biology, hunting practice, safety and retrieval." },
    { id: "source:ontario-hunting-regulations", title: "Ontario hunting regulations summary", publisher: "Government of Ontario", url: "https://www.ontario.ca/document/ontario-hunting-regulations-summary", kind: "REGULATORY_AUTHORITY", reviewedAt: "2026-10-06", note: "Current authority handoff for Ontario rules; page content is not a substitute." },
    { id: "source:north-ground-whitetail-surface", title: "White-tailed deer Species Heat surface 2.1.0", publisher: "North Ground", url: "https://www.northgroundbushcraft.com/hunt?species=white-tailed-deer&explore=1", kind: "GEOSPATIAL", reviewedAt: "2026-10-06", note: "Production-verified range-and-habitat model, methodology, confidence and limitations." },
  ],
  speciesReferences: [{ speciesId: "species:mule-deer", label: "Mule deer", path: "/hunting/species/mule-deer" }],
  huntLinks: { legality: "/hunt?species=white-tailed-deer", map: "/hunt?species=white-tailed-deer&explore=1" },
  visualAssets: [
    { id: "visual:antler-rub", originalPath: "/White tail deer/white-tailed-deer-antler-rub.webp", purpose: "Antler-rub field signs", section: "tracks-and-sign", role: "sign explorer", width: 1536, height: 1024, status: "USED", requirement: "Use as educational artwork, not proof of freshness or current occupancy.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "rub", src: "/species-authority/white-tailed-deer/antler-rub.webp", width: 1536, height: 1024, alt: "Educational plate showing stripped bark, debris and several stages of deer antler rubs", caption: "Antler-rub examples. Confirm species, freshness and use from surrounding sign; the artwork is not field evidence." }] },
    { id: "visual:bed", originalPath: "/White tail deer/white-tailed-deer-bed.webp", purpose: "Deer-bed field signs", section: "tracks-and-sign", role: "sign explorer", width: 1536, height: 1024, status: "USED", requirement: "Pair bed shape with tracks, pellets and surrounding cover.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "bed", src: "/species-authority/white-tailed-deer/bed.webp", width: 1536, height: 1024, alt: "Educational plate showing oval depressions and flattened vegetation associated with deer beds", caption: "A bed is a resting-place clue, not species proof. Read it with tracks, pellets and habitat." }] },
    { id: "visual:bedding-habitat", originalPath: "/White tail deer/white-tailed-deer-bedding habitat.webp", purpose: "Bedding-cover examples", section: "habitat", role: "habitat explorer", width: 1536, height: 1024, status: "USED", requirement: "Describe cover function rather than promise deer presence.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "bedding-habitat", src: "/species-authority/white-tailed-deer/bedding-habitat.webp", width: 1536, height: 1024, alt: "Examples of dense woodland and brush that can provide deer bedding cover", caption: "Potential bedding cover supplies concealment and shelter; fresh sign must confirm current use." }] },
    { id: "visual:browsed-vegetation", originalPath: "/White tail deer/white-tailed-deer-browsed-vegitation.webp", purpose: "Browsed-vegetation signs", section: "tracks-and-sign", role: "sign explorer", width: 1536, height: 1024, status: "USED", requirement: "Do not identify deer from browse alone.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "browse", src: "/species-authority/white-tailed-deer/browsed-vegetation.webp", width: 1536, height: 1024, alt: "Educational plate showing clipped shoots and vegetation browsed by deer", caption: "Browsing shows feeding pressure. Tracks, pellets or observation are needed before assigning it to white-tailed deer." }] },
    { id: "visual:feeding-habitat", originalPath: "/White tail deer/white-tailed-deer-feeding-habitat.webp", purpose: "Seasonal feeding habitat", section: "diet", role: "diet explorer", width: 1536, height: 1024, status: "USED", requirement: "Season dates and foods are examples, not a universal calendar or local prescription.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [
      { id: "feeding-overview", src: "/species-authority/white-tailed-deer/feeding-habitat-by-season.webp", width: 1536, height: 1024, alt: "Four-season educational overview of potential white-tailed deer foods and feeding habitat", caption: "Seasonal feeding overview. Local plant communities, weather and latitude change what is available." },
      { id: "diet-spring", src: "/species-authority/white-tailed-deer/diet-spring.webp", width: 768, height: 1878, alt: "Spring panel showing a deer feeding among emerging forest vegetation", caption: "Spring example: tender green growth and forbs become available as local conditions warm." },
      { id: "diet-summer", src: "/species-authority/white-tailed-deer/diet-summer.webp", width: 768, height: 1878, alt: "Summer panel showing a deer feeding in dense green vegetation", caption: "Summer example: diverse leaves, forbs and crops may be available." },
      { id: "diet-fall", src: "/species-authority/white-tailed-deer/diet-fall.webp", width: 768, height: 1878, alt: "Autumn panel showing a deer foraging on a forest floor", caption: "Autumn example: mast and other energy-rich foods can reorganize movement." },
      { id: "diet-winter", src: "/species-authority/white-tailed-deer/diet-winter.webp", width: 768, height: 1878, alt: "Winter panel showing a deer browsing woody stems in snow", caption: "Winter example: woody browse becomes more important where green forage is limited." },
    ] },
    { id: "visual:identification-buck", originalPath: "/White tail deer/white-tailed-deer-identification-buck.webp", purpose: "Adult buck identification", section: "identification", role: "identification explorer", width: 1536, height: 1024, status: "USED", requirement: "Use several field marks; antlers and body size alone are not decisive.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "identification-buck", src: "/species-authority/white-tailed-deer/identification-buck.webp", width: 1536, height: 1024, alt: "Adult antlered white-tailed deer in side view with the white underside of the tail visible", caption: "Adult buck example. Confirm the broad white tail underside with several other traits." }] },
    { id: "visual:scat", originalPath: "/White tail deer/white-tailed-deer-scat.webp", purpose: "Pellet and scat examples", section: "tracks-and-sign", role: "sign explorer", width: 1536, height: 1024, status: "USED", requirement: "Shape varies with diet and moisture; never age sign precisely from appearance alone.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "scat", src: "/species-authority/white-tailed-deer/scat.webp", width: 1536, height: 1024, alt: "Educational examples of grouped and clumped deer droppings", caption: "Pellet form varies with food and moisture. Context matters more than a single dropping." }] },
    { id: "visual:sex-age", originalPath: "/White tail deer/white-tailed-deer-sex-age-comparison.webp", purpose: "Sex and age comparison", section: "identification", role: "candidate comparison plate", width: 1536, height: 1024, status: "REVIEW_REQUIRED", requirement: "Do not publish: the embedded claim that fawn spots are year-round is false; body-build generalizations are also too absolute.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix." },
    { id: "visual:shot-broadside-anatomy", originalPath: "/White tail deer/white-tailed-deer-shot-broadside-anatomy.webp", purpose: "Broadside internal anatomy", section: "shot-placement", role: "candidate anatomy reference", width: 1675, height: 939, status: "REVIEW_REQUIRED", requirement: "Do not publish until veterinary/anatomical review; it is not registered to the external broadside asset and simplifies digestive anatomy.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix." },
    { id: "visual:shot-broadside-external", originalPath: "/White tail deer/white-tailed-deer-shot-broadside-external.webp", purpose: "Broadside external target region", section: "shot-placement", role: "shot explorer", width: 1536, height: 1024, status: "USED", requirement: "Treat the overlay as a broad heart-lung region, never a universal aiming point.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "shot-broadside-external", src: "/species-authority/white-tailed-deer/shot-broadside-external.webp", width: 1536, height: 1024, alt: "Broadside white-tailed deer with a broad translucent heart-lung target region behind the near shoulder", caption: "Broadside educational target region—not a magic pixel. Account for both legs, angle, distance and the path through the chest." }] },
    { id: "visual:shot-frontal", originalPath: "/White tail deer/white-tailed-deer-shot-frontal-anatomy.webp", purpose: "Frontal shot target and anatomy", section: "shot-placement", role: "candidate shot plate", width: 1536, height: 1024, status: "NOT_USED", requirement: "Not used: the target overlay conflicts with this page's sourced pass/no-shot guidance for frontal presentations.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix." },
    { id: "visual:shot-quartering-toward", originalPath: "/White tail deer/white-tailed-deer-shot-quartering forward-anatomy.webp", purpose: "Quartering-toward target and anatomy", section: "shot-placement", role: "candidate shot plate", width: 1536, height: 1024, status: "NOT_USED", requirement: "Not used: the target overlay conflicts with this page's sourced pass/no-shot guidance for quartering-toward presentations.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix." },
    { id: "visual:shot-quartering-away", originalPath: "/White tail deer/white-tailed-deer-shot-quartering-away-anatomy.webp", purpose: "Quartering-away external and anatomy pair", section: "shot-placement", role: "shot explorer", width: 1536, height: 1024, status: "USED", requirement: "Use only for a modest angle; show external and anatomy halves without stretching and reset the view when angle changes.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [
      { id: "shot-quartering-away-external", src: "/species-authority/white-tailed-deer/shot-quartering-away-external.webp", width: 766, height: 1024, alt: "White-tailed deer at a modest quartering-away angle with a broad translucent heart-lung target region", caption: "Modest quartering-away external view. The correct path crosses the chest; steep angles are a pass." },
      { id: "shot-quartering-away-anatomy", src: "/species-authority/white-tailed-deer/shot-quartering-away-anatomy.webp", width: 766, height: 1024, alt: "Registered anatomy view of a white-tailed deer at a modest quartering-away angle showing ribs, lungs and heart", caption: "Registered anatomy layer from the same pose. It explains the intended chest path; it does not replace judgment." },
    ] },
    { id: "visual:track-patterns", originalPath: "/White tail deer/white-tailed-deer-track-patterns.webp", purpose: "Track-line examples in soil and snow", section: "tracks-and-sign", role: "track subview", width: 1536, height: 1024, status: "USED", requirement: "Conceptual only; the artwork is not scale-calibrated and must not be used to infer sex or exact size.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "track-patterns", src: "/species-authority/white-tailed-deer/track-patterns.webp", width: 1536, height: 1024, alt: "Conceptual side-by-side examples of deer track lines in leaf litter and snow", caption: "Conceptual track-line examples; not to scale. Substrate, speed and gait change the impression." }] },
    { id: "visual:tracks-diagram", originalPath: "/White tail deer/white-tailed-deer-tracks-diagram.webp", purpose: "Track anatomy diagram", section: "tracks-and-sign", role: "candidate track subview", width: 1536, height: 1024, status: "REVIEW_REQUIRED", requirement: "Do not publish: its rounded-tip comparison conflicts with the sourced pointed, heart-shaped field mark and its gait labels need review.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix." },
    { id: "visual:travel-corridor", originalPath: "/White tail deer/white-tailed-deer-travel-corridor.webp", purpose: "Travel-corridor examples", section: "habitat", role: "habitat and sign synthesis", width: 1536, height: 1024, status: "USED", requirement: "A corridor is a hypothesis until current sign confirms use.", provenance: "North Ground original educational artwork; source file contains PNG bytes despite its .webp suffix.", renditions: [{ id: "travel-corridor", src: "/species-authority/white-tailed-deer/travel-corridor.webp", width: 1536, height: 1024, alt: "Examples of narrow trails and cover transitions that may concentrate deer travel", caption: "Potential travel corridors connect needs or narrow movement. Confirm current use from converging fresh sign." }] },
    { id: "visual:white-tail-vs-mule", originalPath: "/White tail deer/white-tailed-deer-vs-mule-deer.webpg.png", purpose: "White-tail and mule deer comparison", section: "identification", role: "identification comparison", width: 1536, height: 1024, status: "USED", requirement: "Use tail, ears, antler branching and gait together; do not rely on the plate's body-build generalizations.", provenance: "North Ground original educational artwork.", renditions: [{ id: "white-tail-vs-mule", src: "/species-authority/white-tailed-deer/white-tail-vs-mule-deer.webp", width: 1536, height: 1024, alt: "Educational comparison of white-tailed deer and mule deer highlighting tail, ear and antler differences", caption: "Comparison aid. Combine tail pattern, ear proportion, antler branching and escape gait; individual traits overlap." }] },
  ],
  visualExplorers: {
    identification: { id: "identification-explorer", sectionId: "identification", title: "Build an identification", intro: "Start with the tail, then confirm several independent traits. A single antler, ear or body-size impression is not enough.", items: [
      { id: "adult-buck", label: "Adult buck", directAnswer: "An antlered adult can show the main-beam antler pattern, but the broad white tail underside remains the stronger species mark.", details: ["Look for tines rising from a main beam.", "Age, nutrition and injury change antler form.", "Shed or obscured antlers make sex-class calls harder."], renditionId: "identification-buck", citations: [c("source:hww-whitetail", "Description")] },
      { id: "mule-deer-comparison", label: "White-tail vs mule deer", directAnswer: "Combine tail pattern, ear proportions, antler branching and escape gait; do not decide from body size alone.", details: ["White-tail: broad white underside, commonly raised when alarmed.", "Mule deer: larger ears, black-tipped narrow tail and forked antlers are common.", "Range overlap and individual variation require a multi-trait decision."], renditionId: "white-tail-vs-mule", caution: "If species or legal animal class is uncertain, do not shoot.", citations: [c("source:ndgf-whitetail", "Identification")] },
    ] },
    habitat: { id: "habitat-explorer", sectionId: "habitat", title: "Read the food–cover pattern", intro: "These are functional habitat categories shown by the supplied assets—not promises that deer are present.", items: [
      { id: "bedding-cover", label: "Bedding cover", directAnswer: "Dense, sheltered cover can provide concealment, thermal protection and a resting place near food.", details: ["Look for security from repeated disturbance.", "In winter, shelter and snow depth can matter as much as concealment.", "Confirm use with beds, tracks or pellets."], renditionId: "bedding-habitat", citations: [c("source:maine-whitetail", "Winter habitat")] },
      { id: "feeding-cover", label: "Feeding habitat", directAnswer: "Openings, edges, wetlands, old fields and forest understories can supply seasonally changing food.", details: ["Availability changes with local plant communities.", "Mast or crops can reorganize autumn movement.", "Food without nearby security cover may see little daylight use."], renditionId: "feeding-overview", citations: [c("source:usfs-feis-whitetail", "Food habits")] },
      { id: "travel-corridors", label: "Travel corridors", directAnswer: "Trails, cover transitions and barriers can connect bedding and feeding needs or narrow movement.", details: ["Map geometry proposes a corridor.", "Repeated, fresh sign confirms present use.", "Plan access so you do not cross the route you intend to watch."], renditionId: "travel-corridor", citations: [c("source:indiana-scouting", "Funnels and travel corridors")] },
    ] },
    diet: { id: "diet-explorer", sectionId: "diet", title: "Food changes with the season", intro: "The calendar is illustrative. Latitude, weather, plant community and agriculture determine what is actually available.", items: [
      { id: "spring", label: "Spring", directAnswer: "Emerging green growth and forbs can become important as dormancy ends.", details: ["Check sun-facing slopes and early openings.", "Tender shoots are examples, not a universal menu."], renditionId: "diet-spring", citations: [c("source:usfs-feis-whitetail", "Food habits")] },
      { id: "summer", label: "Summer", directAnswer: "Leaves, forbs, soft mast and agricultural plants can provide diverse forage.", details: ["Food is often dispersed through abundant cover.", "Local crops and phenology change movement."], renditionId: "diet-summer", citations: [c("source:usfs-feis-whitetail", "Food habits")] },
      { id: "fall", label: "Fall", directAnswer: "Mast, fruit and crops can concentrate feeding where they are abundant.", details: ["Acorn availability can shift routes quickly.", "Confirm the food is present this year, not merely mapped."], renditionId: "diet-fall", citations: [c("source:usfs-feis-whitetail", "Food habits")] },
      { id: "winter", label: "Winter", directAnswer: "Woody browse and sheltered feeding areas become more important when green forage declines.", details: ["Deep snow raises travel costs.", "Avoid needless disturbance around concentrated wintering deer."], renditionId: "diet-winter", citations: [c("source:maine-whitetail", "Winter habitat")] },
    ] },
    signs: { id: "signs-explorer", sectionId: "tracks-and-sign", title: "Read sign in context", intro: "Select a sign, then test it against freshness, repetition, weather and the surrounding food–cover pattern.", items: [
      { id: "tracks", label: "Tracks", directAnswer: "Typical white-tail tracks have two pointed toes and a heart-shaped outline, but soft ground and speed can distort them.", details: ["Follow direction and repetition, not one perfect print.", "Track size cannot establish sex.", "The image is conceptual and not scale-calibrated."], renditionId: "track-patterns", caution: "Use the deeper track view as a pattern aid, never as a ruler.", citations: [c("source:mdc-whitetail", "Tracks")] },
      { id: "beds", label: "Beds", directAnswer: "A flattened oval or body-shaped depression can mark a resting place, but it is not species proof by itself.", details: ["Look for tracks and pellets nearby.", "Repeated beds can reveal a bedding area.", "Do not push animals from sensitive winter cover."], renditionId: "bed", citations: [c("source:indiana-scouting", "Scouting basics")] },
      { id: "rubs", label: "Antler rubs", directAnswer: "Stripped bark and vertical scraping can indicate antler rubbing, usually by an antlered deer.", details: ["Freshness varies with moisture, bark and exposure.", "A rub does not promise daylight use.", "Several rubs may help reveal a route."], renditionId: "rub", citations: [c("source:indiana-scouting", "Rubs and scrapes")] },
      { id: "browse", label: "Browse", directAnswer: "Clipped shoots or a browse line show repeated feeding pressure, not species identity.", details: ["Identify the plant and current availability.", "Pair browse with tracks or pellets.", "Fresh cuts age differently in sun, frost and rain."], renditionId: "browse", citations: [c("source:wdfw-deer", "Signs")] },
      { id: "pellets", label: "Pellets", directAnswer: "Droppings can confirm ungulate use, while shape and clumping vary with diet and moisture.", details: ["Avoid precise age claims from colour alone.", "Note whether deposits repeat along a route.", "Treat scat as supporting evidence, not a population count."], renditionId: "scat", citations: [c("source:wdfw-deer", "Signs")] },
      { id: "synthesis", label: "Several signs together", directAnswer: "Confidence rises when fresh tracks, current browse, pellets and a used trail converge between plausible food and cover.", details: ["One clue suggests; several independent clues support.", "Recent weather provides the ageing context.", "State uncertainty when the evidence conflicts."], renditionId: "travel-corridor", citations: [c("source:indiana-scouting", "Scouting basics")] },
    ] },
    shotPlacement: { id: "shot-placement-explorer", sectionId: "shot-placement", title: "Choose the angle before the target", intro: "First decide whether the presentation permits a controlled path through the heart-lung area. The coloured region is deliberately broad: it is not a universal aiming dot.", legalHandoff: "This explorer does not make a hunt legal. Confirm the exact place, date, licence, animal class, equipment and current authority before hunting.", items: [
      { id: "broadside", label: "Broadside", assessment: "PREFERRED", directAnswer: "A calm, clear broadside presentation offers the most legible path through the chest's heart-lung area.", targetRegion: "the broad chest region immediately behind the near shoulder, adjusted for leg position and the intended exit path", details: ["Confirm both near and far legs.", "Require an unobstructed path and safe backstop.", "Distance must remain inside your proven capability."], renditionId: "shot-broadside-external", registration: "NOT_APPLICABLE", citations: [c("source:illinois-shot", "Heart and lungs")] },
      { id: "quartering-away", label: "Modest quartering-away", assessment: "CONDITIONAL", directAnswer: "A modest quartering-away angle can offer a controlled path through the chest; a steep angle should be passed.", targetRegion: "the near-side chest region that sends the path toward the far shoulder and through both lungs", details: ["Visualize entry and exit, not a surface spot.", "Use the anatomy toggle to understand the path through the same registered pose.", "Pass if the angle becomes steep or the far lung is not credibly on the path."], renditionId: "shot-quartering-away-external", anatomyRenditionId: "shot-quartering-away-anatomy", registration: "REGISTERED_PAIR", citations: [c("source:illinois-shot", "Shot angles")] },
      { id: "frontal", label: "Frontal", assessment: "PASS", directAnswer: "Pass on a frontal presentation: the vital path is narrow and heavy bone or a small angle error raises wounding risk.", targetRegion: "none—wait for a safer presentation", details: ["Do not let proximity substitute for angle quality.", "Keep the muzzle or bow controlled while waiting.", "Let the deer leave if the presentation does not improve."], registration: "NOT_APPLICABLE", citations: [c("source:illinois-shot", "Shot angles")] },
      { id: "quartering-toward", label: "Quartering toward", assessment: "PASS", directAnswer: "Pass when the near shoulder and heavy bone block a dependable path through both lungs.", targetRegion: "none—wait for broadside or modest quartering-away", details: ["A visible chest does not guarantee a clear vital path.", "Steeper angles make the path less forgiving.", "The supplied target plate was excluded because it implied a shot here."], registration: "NOT_APPLICABLE", citations: [c("source:illinois-shot", "Shot angles")] },
      { id: "rear-facing", label: "Rear-facing", assessment: "PASS", directAnswer: "Pass on a rear-facing deer; there is no controlled, ethical path to the heart-lung area.", targetRegion: "none—do not shoot", details: ["Wait without forcing movement.", "Maintain awareness of other hunters and boundaries.", "No image is needed to teach a no-shot decision."], registration: "NOT_APPLICABLE", citations: [c("source:illinois-shot", "Shot angles")] },
    ] },
  },
};
