import evidence from "../../../../content/registry/us-coverage-evidence.generated.json" with { type: "json" };
import mapLicences from "../../../../content/registry/us-map-licence-findings.json" with { type: "json" };
import { licencePermitsServing, licencePermitsStoredCopy } from "../source-licence.ts";
import { layerById } from "../zone-layers.ts";
import { US_LAYER_IDS } from "./layers.ts";
import { UNITED_STATES_JURISDICTIONS } from "./registry.ts";

/**
 * How far each state has actually got, in three lanes that never substitute
 * for one another.
 *
 *   MAP           can Hunt identify the official hunting geography, and is it
 *                 licensed to do so?
 *   REGULATIONS   are the sources sufficient to answer a species on a date in
 *                 a place?
 *   INTELLIGENCE  is there harvest, effort or success evidence? Optional. A
 *                 state with none is not incomplete: it is a state Hunt can
 *                 answer for, without a heat map.
 *
 * Every status here is computed from evidence on disk
 * (`content/registry/us-coverage-evidence.generated.json`, generated by
 * `scripts/build-us-coverage-evidence.mjs`) plus each layer's live licence and
 * serving flags. Nothing is typed: a state cannot be made to look covered by
 * editing a constant, and a bundle that is not certified cannot be promoted by
 * describing it differently.
 */

export type MapCertification =
  /** No reviewed geography service. */
  | "UNAVAILABLE"
  /** A service is registered; its parity with the authority is not certified. */
  | "IN_DEVELOPMENT"
  /** Parity certified, but the publisher grants no use: Hunt will not draw it. */
  | "LICENCE_BLOCKED"
  /**
   * The authority publishes a service North Ground cannot reach SECURELY, so
   * its terms have never been read either.
   *
   * Distinct from LICENCE_BLOCKED, which is a refusal we HAVE read, and from
   * UNAVAILABLE, which means no service was found. Arizona is the first case:
   * its own GIS host has presented an expired certificate since 2022. Calling
   * that licence-blocked would assert something about terms nobody has read;
   * calling it unavailable would deny that the authority publishes a service at
   * all. The remedy also belongs to a different party — the authority renews a
   * certificate; only the publisher can change a licence.
   */
  | "TRANSPORT_BLOCKED"
  /**
   * The publisher's terms permit use and no geometry is ingested yet.
   *
   * This exists because Hawaii arrived and had nowhere to go. A state with a
   * permissive licence already read fell through to UNAVAILABLE, which is the
   * same word used for a state nobody has looked at — so the report could not
   * tell "cleared, not yet built" from "we know nothing". That is not a display
   * nicety: §9 asks coverage to be usable as an execution queue, and a queue
   * that cannot see which states are unblocked cannot order the work.
   *
   * It is deliberately NOT a form of CERTIFIED. Nothing is drawn, nothing is
   * parity-checked, and no hunter can receive anything from it.
   *
   * And it is gated on there being no recorded `servingDecision`. Michigan's
   * licence permits reuse and Michigan still cannot be served, because the
   * instrument rescinding two of its units has not been read. A clear licence
   * is not a clear road, so Michigan stays UNAVAILABLE and its row names the
   * decision instead.
   */
  | "LICENCE_CLEAR_NOT_INGESTED"
  /** Parity certified and licensed; ready to be served. */
  | "CERTIFIED"
  /** Drawn and resolving in production. */
  | "SERVED";

export type RegulationsCertification =
  /** No bundle. Every query is UNKNOWN. */
  | "UNAVAILABLE"
  /** A bundle exists; no cases written from the law confirm it end to end. */
  | "PARTIAL"
  /** Bundle plus certification cases. */
  | "CERTIFIED"
  /** Answering in production. */
  | "SERVED";

export type IntelligenceCertification = "NONE" | "PARTIAL" | "CERTIFIED";

export interface StateCertification {
  code: string;
  map: {
    status: MapCertification;
    layers: Array<{
      layerId: string;
      points: number | null;
      disagreements: number | null;
      certifiedOn: string | null;
      licence: { permittedUse: string; redistribution: string; storedCopyPermitted: boolean } | null;
      serving: boolean;
    }>;
    /** Why it is not further along, in the terms a person would need to act on. */
    /** Why this state stands where it does: what blocks it, or that only the work does. */
    detail: string | null;
  };
  regulations: {
    status: RegulationsCertification;
    bundles: string[];
    rules: number;
    species: string[];
    cases: number;
    rulesServing: boolean;
  };
  intelligence: { status: IntelligenceCertification; datasets: string[] };
}

type ParityRecord = { layerId: string; points: number; disagreements: number; certifiedOn: string };
const parity = evidence.parity as Record<string, ParityRecord[]>;
const cases = evidence.cases as Record<string, { cases: number }>;
const bundles = evidence.bundles as Record<string, Array<{ bundleId: string; rules: number; species: string[] }>>;
const intelligence = evidence.intelligence as Record<string, string[]>;
/* What a state's publisher says about its map data, recorded before any rules
   work is spent there. A state with no layer yet is not simply unexplored if
   we already know its terms refuse us. */
type MapLicenceFinding = {
  state: string; checkedOn: string;
  geography: {
    term: string; service: string;
    /**
     * UNITS, never the layer's feature count.
     *
     * Three states in one pass published a layer whose feature count exceeds
     * its unit system — Hawaii's closures and safety zones, Oregon's two
     * NOT MANAGED polygons, Washington's boundary segments — and the error is
     * always in the direction that looks like more coverage. Where the two
     * differ, `theFeatureCountIsNotTheUnitCount` records why.
     */
    unitCount: number | null; definedBy: string;
    theFeatureCountIsNotTheUnitCount?: string;
    /**
     * A layer whose NAME fits and whose CONCEPT does not.
     *
     * New Jersey's "Deer Management Unit" layer is a sequential 1..632 grid
     * beside its 88 season-setting zones. Distinct from the count problem
     * above: both counts are honest, and only the distinct values of the unit
     * field distinguish them.
     */
    theNamedLayerIsTheWrongCONCEPT?: string;
    /**
     * The layer's coverage stops short of the law's.
     *
     * Florida: Rule 68A-13.0001(2)(a) puts the whole of Monroe County — the
     * Keys — in Zone A, and every DMU is a portion of a Zone. The DMU layer
     * stops at 24.8814°N, so Marathon and Big Pine Key return ZERO features,
     * with the miss persisting at a 30 km tolerance. A point the law places in
     * a zone is NOT thereby closed or zoneless, and §8 forbids discarding the
     * mainland because the lower Keys are unresolvable.
     */
    theLayerStopsShortOfTheLaw?: string;
    /**
     * No authority publishes this geography as vector data at all.
     *
     * Alabama: its deer zones exist only as narrative metes-and-bounds, and
     * ADCNR's 46 services contain no zone layer. Deriving the lines ourselves
     * from highway centrelines and river courses would be North Ground
     * inventing a regulatory boundary, which §41A forbids outright — so this
     * is a genuine evidentiary gap, not an implementation limitation.
     */
    theAbsenceIsTheFinding?: string;
    /** Where the authority fixes the legal boundary somewhere other than its own GIS. */
    theLegalBoundaryIsElsewhere?: string;
    /** The zones sit at a layer id other than 0, which is the usual guess. */
    theLayerIdIsNot0?: string;
    theOutstandingParityCheck?: string;
    fourUnitSystemsAndOnlyOneCarriesTheSeasons?: string;
    threeGeographiesNotOne?: string;
    countyIsNotTheWholeGeography?: string;
    theOneNamedZoneIsComposable?: string;
    theCountyGeometryBELONGSToAnotherAgency?: string;
    bearHasNoGeometryAndItsDefinitionsAreSubCounty?: string;
    /** A field that looks regulatory and is not. Georgia's DMU appears zero times in its own rules. */
    administrativeFieldsThatMustNeverBeServed?: string;
    /** Parity established by comparing SETS, because equal counts can conceal a disagreement. */
    parityCertifiedBySetComparisonNotByCount?: string;
    deerIsTheOnlyZonedSpecies?: string;
    theUnitIdentifierIsNotAStableKey?: string;
    theFederalRouteIsClosedToo?: string;
    typosRunPdfToGisCorrected?: string;
    theScopeLimitMustNotBeFlattened?: string;
    theNameMismatchWouldBreakAResolver?: string;
    theCountyListsReconcileExactly?: string;
    districtIsNotAUnit?: string;
  };
  /**
   * The publisher's terms, where they could be READ. Absent when the service
   * could not be reached at all — see `reachability`. Exactly one of the two is
   * present, which the certification test asserts: a finding with neither is a
   * state somebody started and left.
   */
  licence?: { statedAs: string; url: string; retrievedAt: string; sha256: string; permittedUse: string; redistribution: string; attribution: string | null; note?: string | null };
  /**
   * The AUTHORITY'S RULES HOST refuses the reader, while its map service answers.
   *
   * A different failure from `reachability`, and it must not be put in the map
   * lane: Massachusetts's zone service returns 200 while mass.gov returns 403 to
   * every fetcher, and New Hampshire's GIS item answers while wildlife.nh.gov
   * returns 403 on six paths. Recording either as TRANSPORT_BLOCKED on the map
   * would assert that the map cannot be reached, which is false.
   *
   * It is still a real blocker — §45's source-change detection and hash
   * verification cannot run against a host that will not serve the reader — so
   * it is recorded, just not against the wrong lane.
   */
  rulesReachability?: { state: "TRANSPORT_BLOCKED"; finding: string; evidence: Record<string, unknown>; whyNotWorkedAround: string; whatWouldUnblockIt: string; notTheSameAsLicenceBlocked: string };
  /** Why no licence could be read: the service itself is unreachable. */
  reachability?: { state: "TRANSPORT_BLOCKED"; finding: string; evidence: Record<string, unknown>; whyNotWorkedAround: string; whatWouldUnblockIt: string; notTheSameAsLicenceBlocked: string };
  /**
   * The service is reachable and the publisher has stated NO terms at all.
   *
   * Third of three, and not interchangeable with the others: the next action
   * differs. `licence` means read what it says; `reachability` means ask the
   * authority to fix its certificate; this means ask the authority to state
   * terms at all. Nevada is the near neighbour and still different — it HAS
   * written terms that happen not to mention reuse.
   */
  licenceAbsent?: { state: "NONE_STATED"; finding: string; whereLooked: string[]; controlForTheAbsence: string; whatWouldUnblockIt: string; theTrapAvoided?: string; whyItsOwnStateAndNotReachability?: string };
  /**
   * The authority publishes NO hunting-unit geography that a search could find.
   *
   * Fourth of four, and the one that changes what "no evidence" means. Before
   * any state was searched, a state with no record and a state whose authority
   * genuinely publishes nothing were indistinguishable — both read as
   * UNAVAILABLE with "No reviewed geography service", which is true of the
   * second and misleading about the first. This makes the search itself the
   * evidence, and it must carry what was searched and how many authority
   * accounts were found, or it is a shrug rather than a finding.
   *
   * The map status stays UNAVAILABLE, because there is still nothing to serve.
   * What changes is the DETAIL: a hunter-facing gap that has been looked into
   * reads differently from one nobody has opened.
   */
  searchedNoGeography?: {
    state: "NO_OFFICIAL_UNIT_GEOGRAPHY_FOUND";
    checkedOn: string;
    termsSearched: number;
    portalItemsReviewed: number;
    authorityAccountsFound: string[];
    conclusion: string;
    whatWouldChangeIt: string;
  };
  /** A recorded decision NOT to serve a state whose licence is clear. */
  servingDecision?: { decidedOn: string; state: string; reason: string; askedOfAuthority?: string };
  /**
   * Two of the AUTHORITY'S OWN publications disagree about the same geography.
   *
   * Not a licence problem and not a transport problem — a fourth kind of
   * blocker, and the only one where both copies are authentic. Pennsylvania
   * publishes 11 elk hunt zones from its ArcGIS Online account and 14 from its
   * own server. Picking either would be an invention, so §8's CONFLICT state
   * carries it until the defining instrument is read.
   */
  conflict?: { state: "CONFLICT"; finding: string; whyItIsNotResolvedHere: string; whatWouldResolveIt: string; doNotServeEitherUntilResolved: boolean };
  /**
   * The publisher forbids the specific OPERATION Hunt performs, separately from
   * any reuse terms.
   *
   * Alaska: "Not to be used with GPS to determine physical boundaries." Held
   * apart from the licence because consent to redistribute would not touch it —
   * the two blockers are lifted by different acts, and folding this into the
   * licence note would let an obtained consent read as an unblocked state.
   */
  theTermsAlsoForbidTheUseHuntMakes?: { statedAs: string; finding: string; whyItIsRecordedSeparatelyFromTheLicence: string; notTheSameAsTheUsualCaveat: string };
  /**
   * The authority's own GIS contradicts the authority's own LAW.
   *
   * Distinct from `conflict`, and the difference decides what we do. `conflict`
   * is two hosts of one authority disagreeing with each other, where neither
   * governs and neither is served. Here ONE SIDE GOVERNS — the law does — so
   * the GIS attribute is not served and, where the law yields a servable path,
   * that path is named instead of the state being abandoned.
   *
   * Kentucky is the paradigm and the reason this exists. KDFWR publishes
   * "Annual Deer Management Zones in Kentucky" whose "Current Years Deer Zone"
   * column is byte-identical to its own 2007-08 column, and disagrees with
   * 301 KAR 2:172 for 46 of 120 counties. Every surface signal said current:
   * right publisher, "Annual" in the title, an edit date of 2026-07-10, 120
   * clean county polygons, exactly four zone values. Kentucky's licence is CC0,
   * so NOTHING would have stopped the ingest — which is what makes a clear
   * licence dangerous rather than safe.
   */
  lawVersusGis?: {
    state: "GIS_CONTRADICTS_THE_LAW";
    /**
     * How far the defect reaches, and it changes what we do.
     *
     * WHOLESALE — the attribute is wrong across the layer, so the layer is not
     * served at all. Kentucky: CURRENTZONE is the 2007-08 season everywhere.
     *
     * WHERE_IT_STOPS — the layer is correct where it covers and simply does not
     * reach as far as the law. Florida: the DMU layer is an exact 1:1 match with
     * the twelve codified units and ends at 24.8814°N while the rule reaches to
     * the end of the Keys. Refusing Florida's mainland because its lower Keys
     * are unresolvable is the over-strict error §8 forbids as firmly as a loose
     * claim, so the two cases must not share a consequence.
     */
    defect: "WHOLESALE" | "WHERE_IT_STOPS";
    finding: string;
    lawSays: string;
    gisSays: string;
    /** How the stale side was PROVEN, not inferred. An assertion here is worthless. */
    howTheStaleSideWasProven: string;
    /** What made the wrong side look right, so the next reader is not fooled the same way. */
    everySurfaceSignalSaidCurrent?: string;
    doNotServe: string;
    /** Where the law itself yields a defensible geography, so the state is not abandoned (§8). */
    servablePathFromTheLaw?: string;
  };
  /**
   * Terms found in the portal item's `description` rather than its
   * `licenseInfo`.
   *
   * A fourth place terms hide, and the only one that produces a FALSE GREEN
   * LIGHT: Arkansas's `licenseInfo` is a boundary-accuracy disclaimer, which
   * blocks nothing, while the express limitation of permitted use sits in
   * `description`. Reading the licence field alone would have cleared a state
   * whose data may not be used.
   */
  termsInTheDescriptionField?: { statedAs: string; whyItMatters: string; whatTheLicenceFieldSaidInstead: string };
  /**
   * A jurisdiction that can be answered COMPLETELY, now, on evidence.
   *
   * The District of Columbia is the first in the United States: its substantive
   * game-law provisions were repealed, 19 DCMR § 1560.1 protects all wildlife
   * and the chapter authorises no taking, DC is in no federal flyway, and its
   * firearm-discharge prohibition has no hunting exception. Reporting that as
   * UNKNOWN would understate what the authority establishes — the under-claim
   * direction §8 says nobody ever reports.
   */
  completableNow?: { finding: string; whyItMustNotBeServedAsUNKNOWN: string; hours?: string };
  /** The authority disclaims its own geometry's fidelity for the use Hunt makes of it. */
  boundaryFidelityIsTheBlocker?: { statedAs: string; finding: string; separateFromTheLicence: string };
  /**
   * A permissive-looking licence that belongs to a DIFFERENT publisher, carried
   * by an authoring template.
   *
   * The most dangerous shape found, because it reads as a grant. Kansas's deer
   * items carry U.S. Census Bureau TIGER/Line boilerplate — "not copyrighted",
   * "free to use in a product or publication" — and reporting it would have
   * given Kansas a permissive licence it never issued. Caught because the
   * identical 775-character string sits on six unrelated items created years
   * apart, beside item descriptions listing 2010 census population fields that
   * exist in none of the layers.
   */
  theInheritedLicenceThatIsNotTheirs?: { statedAs: string; finding: string; howItWasCaught: string; andItIsEvidenceAgainstFitness: string; theNarrowProhibitionThatIsKdwps?: string };
  /**
   * One service, one account, one publication window — and a different licence
   * state per dataset.
   *
   * Vermont is the sharpest case: its Wildlife Management Units carry CC BY-SA
   * while its Waterfowl Hunting Zones and State Game Refuges, in the same
   * service, state nothing at all. A state like this cannot be classified once,
   * and borrowing the granted dataset's terms onto the silent ones would be a
   * false claim in the permissive direction.
   */
  termsDifferPerDatasetInOneService?: { finding: string; andEvenWithinOneDatasetFamily?: string; consequence: string };
  /**
   * A terms page that returns HTTP 200 and does not exist.
   *
   * ArcGIS Hub answers 200 for any unknown slug, so a plausible URL "works".
   * Vermont's was caught by byte count against a page that IS in the site's own
   * registry — 65,865 against 65,868, the identical shell. This is the output
   * that otherwise gets reported as a terms page.
   */
  theTermsPageThatReturns200AndDoesNotExist?: { finding: string; provenTwoWays: string; andOnePageIsGenuinelyUnread?: string };
  /**
   * The rules host serves a certificate chain some clients reject.
   *
   * NOT a blocker, and recorded so nobody files it as one. Mississippi omits its
   * intermediate certificate: Node's fetch refuses it while curl and browsers
   * accept the same URL with HTTP 200 and 268,866 bytes. Distinct from Arizona,
   * which serves a certificate EXPIRED since 2022 that no client should accept.
   * The first run of `scripts/check-us-source-urls.mjs` reported Mississippi as
   * unreachable, because `fetch` calls every transport failure "fetch failed".
   */
  rulesHostTlsProblem?: { state: "INCOMPLETE_CERTIFICATE_CHAIN"; finding: string; whyItIsNotRecordedAsABLOCKER: string; howItDiffersFromArizona: string; consequenceForIngestion: string };
  /** A permissive licence attached to the wrong object — a Hub site application rather than a dataset. */
  theHubSiteLicenceIsNotTheDatasetsLicence?: { statedAs: string; finding: string; whatItIsEvidenceOf: string; andOneLicenceFieldIsACurrencyWarning?: string };
  /** The geometry North Ground needs has a different publisher, with its own terms. */
  theCountyGeometryBelongsToAnotherAgency?: { finding: string; whyItIsRecordedSeparately: string };
  /** Rules finer than the only published geography, where a point-in-polygon answer is confidently wrong. */
  threeFinerThanCountyRulesWithNoGeometry?: Record<string, string>;
  /** A restricted geography that is the union of certified units, so it needs no polygon of its own. */
  theCwdZoneIsDerivable?: Record<string, string>;
  /** An hours finding recorded beside the map, where the hours registry's one-basis-per-state shape cannot hold it. */
  legalHours?: { finding: string; contrastWithKentucky?: string; threeThingsThatBreakASingleModel?: string[]; whyNoStateLevelHoursRecordWasAdded?: string };
  /** §41B evidence noticed during a map sweep, recorded without being acted on. */
  speciesHeatCandidate?: { service: string; finding: string; doNotActOnItYet: string };
  /** Measured, because §51 makes speed a gate and an unmeasured claim is not one. */
  measuredPerformance?: Record<string, string>;
  /** A separate artifact whose terms are a different question, kept from being merged. */
  separateInstrumentNotMerged?: { artifact: string; finding: string };
  termsReadElsewhere?: Record<string, unknown>;
  note?: string;
};
const findings = new Map((mapLicences.findings as MapLicenceFinding[]).map((finding) => [finding.state, finding]));

/** Every state whose map licence has been read, whether or not it has a layer. */
export function mapLicenceFindingFor(code: string): MapLicenceFinding | undefined {
  return findings.get(code.toUpperCase());
}

function stateOfLayer(layerId: string): string {
  return layerId.slice("layer:us-".length, layerId.indexOf("-", "layer:us-".length)).toUpperCase();
}

/** Every state that has a registered layer, a bundle or a parity record. */
export function statesWithEvidence(): string[] {
  return [...new Set([
    ...US_LAYER_IDS.map(stateOfLayer),
    ...Object.keys(parity),
    ...Object.keys(bundles),
    ...findings.keys(),
  ])].sort();
}

/**
 * What would actually unblock a state, which is not the same question for all
 * of them. A publisher that says nothing may simply never have been asked; a
 * publisher that forbids commercial use has answered, and reading its terms
 * again will not change the answer. Reporting both as "ask the publisher"
 * would make a refusal look like an errand.
 */
function remedyFor(finding: MapLicenceFinding): string {
  /* A finding with no licence has no licence remedy — it has a reachability
     one, which the caller states instead. Reached only where a licence exists. */
  if (!finding.licence) return finding.reachability?.whatWouldUnblockIt ?? "no remedy recorded.";
  return finding.licence.permittedUse === "RESTRICTED" || finding.licence.redistribution === "PROHIBITED"
    ? "the publisher's own terms refuse this use; only a written exception from it would change that."
    : "no grant is stated either way; a person must ask the publisher.";
}

/**
 * A row says what was CHECKED, or it says nothing.
 *
 * Both of this report's wrong answers came from the same place: a check that
 * answered a narrower question than its wording implied.
 *
 *  - Michigan's row read "Nothing blocks this state but the work" because a
 *    clean licence was the only blocker the report could see. It was false,
 *    and it was the sentence that would have sent the next agent to build
 *    Michigan on minutes that are not an instrument.
 *  - The readiness report called Ontario's hunter-orange rule NOT_CERTIFIED
 *    while eight certified rules sat in the bundle, because it read an object
 *    as an array.
 *
 * Opposite directions, one cause. A report that can only see one kind of
 * blocker will confidently report the absence of every other kind, and
 * under-claiming teaches people to distrust the report, which gets it
 * overridden by hand. So a detail line states the thing it actually
 * established — never a summary that implies more was looked at.
 */
export function certificationFor(code: string): StateCertification {
  const state = code.toUpperCase();
  const layerIds = US_LAYER_IDS.filter((layerId) => stateOfLayer(layerId) === state);
  const records = parity[state] ?? [];

  const layers = layerIds.map((layerId) => {
    const layer = layerById(layerId);
    const record = records.find((entry) => entry.layerId === layerId);
    return {
      layerId,
      points: record?.points ?? null,
      disagreements: record?.disagreements ?? null,
      certifiedOn: record?.certifiedOn ?? null,
      licence: layer?.licence
        ? {
            permittedUse: layer.licence.permittedUse,
            redistribution: layer.licence.redistribution ?? "UNRESOLVED",
            storedCopyPermitted: licencePermitsStoredCopy(layer.licence),
          }
        : null,
      serving: layer?.serving === true,
    };
  });

  /* A state's map is only as certified as its weakest registered layer: a
     second geography Hunt cannot place a point in is not a detail. */
  const certifiedParity = layers.length > 0 && layers.every((entry) => entry.points !== null && entry.points > 0 && entry.disagreements === 0);
  const licensed = layerIds.length > 0 && layerIds.every((layerId) => licencePermitsServing(layerById(layerId)?.licence));
  const unlicensed = layerIds.filter((layerId) => !licencePermitsServing(layerById(layerId)?.licence));
  /* A state with no layer but a licence already read is not "unavailable" in
     the sense of unknown: we know what stands in the way. */
  const finding = findings.get(state);
  const findingPermits = finding?.licence ? ["COMMERCIAL_PERMITTED", "PUBLIC_DOMAIN"].includes(finding.licence.permittedUse) : undefined;
  const map: MapCertification = layerIds.length === 0
    ? (finding?.reachability ? "TRANSPORT_BLOCKED"
        : finding?.licenceAbsent ? "LICENCE_BLOCKED"
        : finding?.licence && findingPermits && !finding.servingDecision ? "LICENCE_CLEAR_NOT_INGESTED"
        : finding?.licence && !findingPermits ? "LICENCE_BLOCKED" : "UNAVAILABLE")
    : !certifiedParity
      ? "IN_DEVELOPMENT"
      : !licensed
        ? "LICENCE_BLOCKED"
        : layers.every((entry) => entry.serving)
          ? "SERVED"
          : "CERTIFIED";
  const detail = finding?.searchedNoGeography && layerIds.length === 0
    ? `Searched ${finding.searchedNoGeography.termsSearched} unit terms across the authority's portal accounts on ${finding.searchedNoGeography.checkedOn} and reviewed ${finding.searchedNoGeography.portalItemsReviewed} published items. ${finding.searchedNoGeography.conclusion} ${finding.searchedNoGeography.whatWouldChangeIt}`
    : finding?.licenceAbsent && layerIds.length === 0
    ? `${finding.licenceAbsent.finding} ${finding.licenceAbsent.whatWouldUnblockIt}`
    : map === "TRANSPORT_BLOCKED"
    ? `${finding!.reachability!.finding} ${finding!.reachability!.whatWouldUnblockIt} No licence claim is made in either direction: the service was never read, so its terms were never read.`
    : map === "LICENCE_BLOCKED"
    ? (layerIds.length === 0 && finding?.licence
        ? `${finding.licence.permittedUse} for ${finding.geography.term} (${finding.geography.unitCount ?? "?"} units), read ${finding.licence.retrievedAt}: "${finding.licence.statedAs.slice(0, 120)}…" — ${remedyFor(finding)}`
        : `No reuse grant recorded for ${unlicensed.join(", ")}; a person must resolve it with the publisher.`)
    : map === "IN_DEVELOPMENT"
      ? "No clean live-parity certification recorded."
      : map === "UNAVAILABLE" || map === "LICENCE_CLEAR_NOT_INGESTED"
        /* A cleared licence is the one kind of "not built yet" worth telling
           apart from the other 43: nothing stands in the way but the work. */
        ? (finding?.servingDecision
            /* A cleared licence does not mean nothing else stands in the way.
               Michigan's licence is clean and Michigan still cannot be served,
               because the instrument rescinding two of its units has not been
               read. Saying "nothing blocks this but the work" there would send
               the next agent to build it. */
            ? `${finding.servingDecision.reason}${finding.servingDecision.askedOfAuthority ? ` Asked of the authority: ${finding.servingDecision.askedOfAuthority}` : ""}`
            : finding && findingPermits
              /* A cleared state's row must carry a recorded do-not-serve, or the
                 sentence "nothing blocks this but the work" sends the next agent
                 to ingest the very layer that is wrong. Kentucky is the case:
                 CC0 licence, 120 clean county polygons, and a zone column that
                 is the 2007-08 season. The licence is what makes it dangerous. */
              ? `Licence permits reuse (${finding.licence!.permittedUse}), read ${finding.licence!.retrievedAt}; ${finding.geography.term} reviewed (${finding.geography.unitCount ?? "?"} units). ${
                  finding.lawVersusGis
                    ? `${finding.lawVersusGis.defect === "WHOLESALE" ? "DO NOT SERVE AS PUBLISHED" : "SERVABLE, WITH A RECORDED GAP"}: ${finding.lawVersusGis.doNotServe}${finding.lawVersusGis.servablePathFromTheLaw ? ` Servable path: ${finding.lawVersusGis.servablePathFromTheLaw}` : ""}`
                    : "Nothing blocks this state but the work."
                }`
              : "No reviewed geography service.")
        : null;

  const stateBundles = bundles[state] ?? [];
  const rulesServing = layerIds.some((layerId) => layerById(layerId)?.rulesServing === true);
  const caseCount = cases[state]?.cases ?? 0;
  const regulations: RegulationsCertification = stateBundles.length === 0
    ? "UNAVAILABLE"
    : caseCount === 0
      ? "PARTIAL"
      : rulesServing
        ? "SERVED"
        : "CERTIFIED";

  return {
    code: state,
    map: { status: map, layers, detail },
    regulations: {
      status: regulations,
      bundles: stateBundles.map((bundle) => bundle.bundleId),
      rules: stateBundles.reduce((total, bundle) => total + bundle.rules, 0),
      species: [...new Set(stateBundles.flatMap((bundle) => bundle.species))].sort(),
      cases: caseCount,
      rulesServing,
    },
    // No state has a certified evidence set yet, and none is required to serve.
    intelligence: { status: (intelligence[state]?.length ?? 0) > 0 ? "PARTIAL" : "NONE", datasets: intelligence[state] ?? [] },
  };
}

export interface UnitedStatesCertificationSummary {
  states: StateCertification[];
  totals: {
    map: Record<MapCertification, number>;
    regulations: Record<RegulationsCertification, number>;
    intelligence: Record<IntelligenceCertification, number>;
  };
  /** States whose only remaining obstacle is a licence a person must resolve. */
  licenceBlocked: Array<{ code: string; blockedBy: string }>;
}

/**
 * The three lanes for every state and D.C., plus counts. A state with no
 * evidence is an explicit UNAVAILABLE row, never absence from the matrix.
 */
export function unitedStatesCertification(): UnitedStatesCertificationSummary {
  const states = UNITED_STATES_JURISDICTIONS
    .filter((entry) => entry.kind !== "federal")
    .map((entry) => certificationFor(entry.code.slice(3)));
  const count = <T extends string>(values: readonly T[], of: (entry: StateCertification) => T): Record<T, number> =>
    Object.fromEntries(values.map((value) => [value, states.filter((entry) => of(entry) === value).length])) as Record<T, number>;
  return {
    states,
    totals: {
      map: count(["UNAVAILABLE", "IN_DEVELOPMENT", "LICENCE_BLOCKED", "TRANSPORT_BLOCKED", "LICENCE_CLEAR_NOT_INGESTED", "CERTIFIED", "SERVED"] as const, (entry) => entry.map.status),
      regulations: count(["UNAVAILABLE", "PARTIAL", "CERTIFIED", "SERVED"] as const, (entry) => entry.regulations.status),
      intelligence: count(["NONE", "PARTIAL", "CERTIFIED"] as const, (entry) => entry.intelligence.status),
    },
    licenceBlocked: states
      .filter((entry) => entry.map.status === "LICENCE_BLOCKED")
      .map((entry) => ({ code: entry.code, blockedBy: entry.map.detail! })),
  };
}
