import evidence from "../../../../content/registry/us-coverage-evidence.generated.json" with { type: "json" };
import mapLicences from "../../../../content/registry/us-map-licence-findings.json" with { type: "json" };
import { licencePermitsServing, licencePermitsStoredCopy } from "../source-licence.ts";
import { layerById } from "../zone-layers.ts";
import { US_LAYER_IDS } from "./layers.ts";

/**
 * How far each state has actually got, in three lanes that never substitute
 * for one another.
 *
 *   MAP           can Hunt identify the official hunting geography, and is it
 *                 licensed to do so?
 *   REGULATIONS   are the sources sufficient to answer a species on a date in
 *                 a place?
 *   INTELLIGENCE  is there harvest, effort or success evidence? Optional. A
 *                 state with none is not incomplete: it is a state Hunt can
 *                 answer for, without a heat map.
 *
 * Every status here is computed from evidence on disk
 * (`content/registry/us-coverage-evidence.generated.json`, generated by
 * `scripts/build-us-coverage-evidence.mjs`) plus each layer's live licence and
 * serving flags. Nothing is typed: a state cannot be made to look covered by
 * editing a constant, and a bundle that is not certified cannot be promoted by
 * describing it differently.
 */

export type MapCertification =
  /** No reviewed geography service. */
  | "UNAVAILABLE"
  /** A service is registered; its parity with the authority is not certified. */
  | "IN_DEVELOPMENT"
  /** Parity certified, but the publisher grants no use: Hunt will not draw it. */
  | "LICENCE_BLOCKED"
  /** Parity certified and licensed; ready to be served. */
  | "CERTIFIED"
  /** Drawn and resolving in production. */
  | "SERVED";

export type RegulationsCertification =
  /** No bundle. Every query is UNKNOWN. */
  | "UNAVAILABLE"
  /** A bundle exists; no cases written from the law confirm it end to end. */
  | "PARTIAL"
  /** Bundle plus certification cases. */
  | "CERTIFIED"
  /** Answering in production. */
  | "SERVED";

export type IntelligenceCertification = "NONE" | "PARTIAL" | "CERTIFIED";

export interface StateCertification {
  code: string;
  map: {
    status: MapCertification;
    layers: Array<{
      layerId: string;
      points: number | null;
      disagreements: number | null;
      certifiedOn: string | null;
      licence: { permittedUse: string; redistribution: string; storedCopyPermitted: boolean } | null;
      serving: boolean;
    }>;
    /** Why it is not further along, in the terms a person would need to act on. */
    /** Why this state stands where it does: what blocks it, or that only the work does. */
    detail: string | null;
  };
  regulations: {
    status: RegulationsCertification;
    bundles: string[];
    rules: number;
    species: string[];
    cases: number;
    rulesServing: boolean;
  };
  intelligence: { status: IntelligenceCertification; datasets: string[] };
}

type ParityRecord = { layerId: string; points: number; disagreements: number; certifiedOn: string };
const parity = evidence.parity as Record<string, ParityRecord[]>;
const cases = evidence.cases as Record<string, { cases: number }>;
const bundles = evidence.bundles as Record<string, Array<{ bundleId: string; rules: number; species: string[] }>>;
const intelligence = evidence.intelligence as Record<string, string[]>;
/* What a state's publisher says about its map data, recorded before any rules
   work is spent there. A state with no layer yet is not simply unexplored if
   we already know its terms refuse us. */
type MapLicenceFinding = {
  state: string; checkedOn: string;
  geography: { term: string; service: string; unitCount: number | null; definedBy: string };
  licence: { statedAs: string; url: string; retrievedAt: string; sha256: string; permittedUse: string; redistribution: string; attribution: string | null; note?: string | null };
  /** A recorded decision NOT to serve a state whose licence is clear. */
  servingDecision?: { decidedOn: string; state: string; reason: string; askedOfAuthority?: string };
};
const findings = new Map((mapLicences.findings as MapLicenceFinding[]).map((finding) => [finding.state, finding]));

/** Every state whose map licence has been read, whether or not it has a layer. */
export function mapLicenceFindingFor(code: string): MapLicenceFinding | undefined {
  return findings.get(code.toUpperCase());
}

function stateOfLayer(layerId: string): string {
  return layerId.slice("layer:us-".length, layerId.indexOf("-", "layer:us-".length)).toUpperCase();
}

/** Every state that has a registered layer, a bundle or a parity record. */
export function statesWithEvidence(): string[] {
  return [...new Set([
    ...US_LAYER_IDS.map(stateOfLayer),
    ...Object.keys(parity),
    ...Object.keys(bundles),
    ...findings.keys(),
  ])].sort();
}

/**
 * What would actually unblock a state, which is not the same question for all
 * of them. A publisher that says nothing may simply never have been asked; a
 * publisher that forbids commercial use has answered, and reading its terms
 * again will not change the answer. Reporting both as "ask the publisher"
 * would make a refusal look like an errand.
 */
function remedyFor(finding: MapLicenceFinding): string {
  return finding.licence.permittedUse === "RESTRICTED" || finding.licence.redistribution === "PROHIBITED"
    ? "the publisher's own terms refuse this use; only a written exception from it would change that."
    : "no grant is stated either way; a person must ask the publisher.";
}

export function certificationFor(code: string): StateCertification {
  const state = code.toUpperCase();
  const layerIds = US_LAYER_IDS.filter((layerId) => stateOfLayer(layerId) === state);
  const records = parity[state] ?? [];

  const layers = layerIds.map((layerId) => {
    const layer = layerById(layerId);
    const record = records.find((entry) => entry.layerId === layerId);
    return {
      layerId,
      points: record?.points ?? null,
      disagreements: record?.disagreements ?? null,
      certifiedOn: record?.certifiedOn ?? null,
      licence: layer?.licence
        ? {
            permittedUse: layer.licence.permittedUse,
            redistribution: layer.licence.redistribution ?? "UNRESOLVED",
            storedCopyPermitted: licencePermitsStoredCopy(layer.licence),
          }
        : null,
      serving: layer?.serving === true,
    };
  });

  /* A state's map is only as certified as its weakest registered layer: a
     second geography Hunt cannot place a point in is not a detail. */
  const certifiedParity = layers.length > 0 && layers.every((entry) => entry.points !== null && entry.points > 0 && entry.disagreements === 0);
  const licensed = layerIds.length > 0 && layerIds.every((layerId) => licencePermitsServing(layerById(layerId)?.licence));
  const unlicensed = layerIds.filter((layerId) => !licencePermitsServing(layerById(layerId)?.licence));
  /* A state with no layer but a licence already read is not "unavailable" in
     the sense of unknown: we know what stands in the way. */
  const finding = findings.get(state);
  const findingPermits = finding ? ["COMMERCIAL_PERMITTED", "PUBLIC_DOMAIN"].includes(finding.licence.permittedUse) : undefined;
  const map: MapCertification = layerIds.length === 0
    ? (finding && !findingPermits ? "LICENCE_BLOCKED" : "UNAVAILABLE")
    : !certifiedParity
      ? "IN_DEVELOPMENT"
      : !licensed
        ? "LICENCE_BLOCKED"
        : layers.every((entry) => entry.serving)
          ? "SERVED"
          : "CERTIFIED";
  const detail = map === "LICENCE_BLOCKED"
    ? (layerIds.length === 0 && finding
        ? `${finding.licence.permittedUse} for ${finding.geography.term} (${finding.geography.unitCount ?? "?"} units), read ${finding.licence.retrievedAt}: "${finding.licence.statedAs.slice(0, 120)}…" — ${remedyFor(finding)}`
        : `No reuse grant recorded for ${unlicensed.join(", ")}; a person must resolve it with the publisher.`)
    : map === "IN_DEVELOPMENT"
      ? "No clean live-parity certification recorded."
      : map === "UNAVAILABLE"
        /* A cleared licence is the one kind of "not built yet" worth telling
           apart from the other 43: nothing stands in the way but the work. */
        ? (finding?.servingDecision
            /* A cleared licence does not mean nothing else stands in the way.
               Michigan's licence is clean and Michigan still cannot be served,
               because the instrument rescinding two of its units has not been
               read. Saying "nothing blocks this but the work" there would send
               the next agent to build it. */
            ? `${finding.servingDecision.reason}${finding.servingDecision.askedOfAuthority ? ` Asked of the authority: ${finding.servingDecision.askedOfAuthority}` : ""}`
            : finding && findingPermits
              ? `Licence permits reuse (${finding.licence.permittedUse}), read ${finding.licence.retrievedAt}; ${finding.geography.term} reviewed (${finding.geography.unitCount ?? "?"} units). Nothing blocks this state but the work.`
              : "No reviewed geography service.")
        : null;

  const stateBundles = bundles[state] ?? [];
  const rulesServing = layerIds.some((layerId) => layerById(layerId)?.rulesServing === true);
  const caseCount = cases[state]?.cases ?? 0;
  const regulations: RegulationsCertification = stateBundles.length === 0
    ? "UNAVAILABLE"
    : caseCount === 0
      ? "PARTIAL"
      : rulesServing
        ? "SERVED"
        : "CERTIFIED";

  return {
    code: state,
    map: { status: map, layers, detail },
    regulations: {
      status: regulations,
      bundles: stateBundles.map((bundle) => bundle.bundleId),
      rules: stateBundles.reduce((total, bundle) => total + bundle.rules, 0),
      species: [...new Set(stateBundles.flatMap((bundle) => bundle.species))].sort(),
      cases: caseCount,
      rulesServing,
    },
    // No state has a certified evidence set yet, and none is required to serve.
    intelligence: { status: (intelligence[state]?.length ?? 0) > 0 ? "PARTIAL" : "NONE", datasets: intelligence[state] ?? [] },
  };
}

export interface UnitedStatesCertificationSummary {
  states: StateCertification[];
  totals: {
    map: Record<MapCertification, number>;
    regulations: Record<RegulationsCertification, number>;
    intelligence: Record<IntelligenceCertification, number>;
  };
  /** States whose only remaining obstacle is a licence a person must resolve. */
  licenceBlocked: Array<{ code: string; blockedBy: string }>;
}

/**
 * The three lanes for every state with any evidence, plus counts. States with
 * no evidence are UNAVAILABLE on every lane and are counted through
 * `unitedStatesCoverageReport`, which knows the full list of 51.
 */
export function unitedStatesCertification(): UnitedStatesCertificationSummary {
  const states = statesWithEvidence().map(certificationFor);
  const count = <T extends string>(values: readonly T[], of: (entry: StateCertification) => T): Record<T, number> =>
    Object.fromEntries(values.map((value) => [value, states.filter((entry) => of(entry) === value).length])) as Record<T, number>;
  return {
    states,
    totals: {
      map: count(["UNAVAILABLE", "IN_DEVELOPMENT", "LICENCE_BLOCKED", "CERTIFIED", "SERVED"] as const, (entry) => entry.map.status),
      regulations: count(["UNAVAILABLE", "PARTIAL", "CERTIFIED", "SERVED"] as const, (entry) => entry.regulations.status),
      intelligence: count(["NONE", "PARTIAL", "CERTIFIED"] as const, (entry) => entry.intelligence.status),
    },
    licenceBlocked: states
      .filter((entry) => entry.map.status === "LICENCE_BLOCKED")
      .map((entry) => ({ code: entry.code, blockedBy: entry.map.detail! })),
  };
}
